### ISSUE TITLE
报错 

### ISSUE THREAD

**Issue by ghost** [FBerthelot/nuxt-seo-module#2]
FATAL  Cannot read property 'map' of undefined                                                                                               00:44:21

  at ModuleContainer.module.exports (node_modules/nuxt-seo-module/src/index.js:22:51)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:190:34)
  at promise.then (node_modules/@nuxt/utils/dist/utils.js:1790:43)

(node:9163) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at ModuleContainer.module.exports (/Users/gyc/Documents/youyiku/vip-free-pc/node_modules/nuxt-seo-module/src/index.js:22:51)
    at ModuleContainer.addModule (/Users/gyc/Documents/youyiku/vip-free-pc/node_modules/@nuxt/core/dist/core.js:190:34)
    at promise.then (/Users/gyc/Documents/youyiku/vip-free-pc/node_modules/@nuxt/utils/dist/utils.js:1790:43)
(node:9163) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:9163) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by FBerthelot** [comment]
Hello @grand-china,

First of all, many thanks for your contribution :)

Without some context it will be hard to help you. I've made this module for nuxt v1, I will try to use my module with nuxt v2, maybe the error come from there.

If you can be more precise, it would be great.

Thank you,

**Comment by ghost** [comment]
$ node -v
v10.15.3

windows 7,

"nuxt": "^2.4.0",

ok , that is all ..
